import sys
from pathlib import Path

# Make src/ importable without an install step
_src = str(Path(__file__).parent.parent / 'src')
if _src not in sys.path:
    sys.path.insert(0, _src)

import pytest

SAMPLE_LOG_LINES = [
    # Failed password for root
    "Apr 23 10:00:01 server1 sshd[1234]: Failed password for root from 1.2.3.4 port 22 ssh2",
    # Failed password for invalid user
    "Apr 23 10:00:05 server1 sshd[1235]: Failed password for invalid user admin from 5.6.7.8 port 22 ssh2",
    # Accepted password
    "Apr 23 10:01:00 server1 sshd[1236]: Accepted password for alice from 10.0.0.1 port 22 ssh2",
    # Accepted publickey
    "Apr 23 10:01:30 server1 sshd[1237]: Accepted publickey for bob from 10.0.0.2 port 22 ssh2",
    # Invalid user
    "Apr 23 10:02:00 server1 sshd[1238]: Invalid user nobody from 9.8.7.6 port 22",
    # Connection closed by invalid user
    "Apr 23 10:02:10 server1 sshd[1238]: Connection closed by invalid user nobody 9.8.7.6 port 22",
    # Disconnected from invalid user
    "Apr 23 10:03:00 server1 sshd[1239]: Disconnected from invalid user testuser 1.1.1.1 port 22",
    # Session opened
    "Apr 23 10:04:00 server1 sshd[1236]: pam_unix(sshd:session): session opened for user alice by (uid=0)",
    # Session closed
    "Apr 23 10:04:30 server1 sshd[1236]: pam_unix(sshd:session): session closed for user alice",
    # Sudo command
    "Apr 23 10:05:00 server1 sudo[5678]: alice : TTY=pts/0 ; PWD=/home/alice ; USER=root ; COMMAND=/bin/ls",
    # Auth failure
    "Apr 23 10:06:00 server1 sshd[1240]: pam_unix(sshd:auth): authentication failure; logname= uid=0 tty=ssh ruser= rhost=2.3.4.5  user=mallory",
    # Unclassified (Other)
    "Apr 23 10:07:00 server1 kernel[0]: Some unrelated kernel message here",
    # Malformed line (no regex match)
    "this is not a valid auth.log line",
]


@pytest.fixture
def sample_log(tmp_path) -> Path:
    """Write SAMPLE_LOG_LINES to a temp file and return its path."""
    log_file = tmp_path / "auth.log"
    log_file.write_text('\n'.join(SAMPLE_LOG_LINES) + '\n', encoding='utf-8')
    return log_file


@pytest.fixture
def empty_log(tmp_path) -> Path:
    log_file = tmp_path / "empty.log"
    log_file.write_text('', encoding='utf-8')
    return log_file


@pytest.fixture
def brute_force_log(tmp_path) -> Path:
    """10 failed attempts from one IP, then a successful login."""
    lines = [
        f"Apr 23 10:0{i}:00 server1 sshd[100{i}]: Failed password for root from 9.9.9.9 port 22 ssh2"
        for i in range(10)
    ]
    lines.append(
        "Apr 23 10:10:00 server1 sshd[1099]: Accepted password for root from 9.9.9.9 port 22 ssh2"
    )
    log_file = tmp_path / "brute.log"
    log_file.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return log_file


@pytest.fixture
def lab_log(tmp_path) -> Path:
    """Full multi-stage attack log generated by generate_lab.py."""
    from generate_lab import generate_lab
    return generate_lab(output_path=tmp_path / 'lab_attack.log')


@pytest.fixture
def syslog_log(tmp_path) -> Path:
    from generate_lab import generate_syslog_lab
    return generate_syslog_lab(output_path=tmp_path / 'lab_syslog.log')


@pytest.fixture
def audit_log(tmp_path) -> Path:
    from generate_lab import generate_audit_lab
    return generate_audit_lab(output_path=tmp_path / 'lab_audit.log')


@pytest.fixture
def web_log(tmp_path) -> Path:
    from generate_lab import generate_web_lab
    return generate_web_lab(output_path=tmp_path / 'lab_web.log')
